# Codecov 配置
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: auto
        threshold: 5%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

flags:
  backend:
    paths:
      - backend/
      - core/
    carryforward: true
  frontend:
    paths:
      - frontend/src/
    carryforward: true

ignore:
  - "**/__pycache__/**"
  - "**/node_modules/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/test_*.py"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/setup.ts"
  - "**/mocks/**"
